wandb_version: 1

dataset:
  desc: null
  value: mnist
architecture:
  desc: null
  value: CNN_GAP
initial_lr:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 10
batch size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702650122.762939
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
    visualize:
      Gradient Magnitudes Epoch 0:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 0
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 0_table
                fields: []
      Gradient Magnitudes Epoch 1:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 1
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 1_table
                fields: []
      Gradient Magnitudes Epoch 2:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 2
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 2_table
                fields: []
      Gradient Magnitudes Epoch 3:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 3
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 3_table
                fields: []
      Gradient Magnitudes Epoch 4:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 4
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 4_table
                fields: []
      Gradient Magnitudes Epoch 5:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 5
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 5_table
                fields: []
      Gradient Magnitudes Epoch 6:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 6
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 6_table
                fields: []
      Gradient Magnitudes Epoch 7:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 7
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 7_table
                fields: []
      Gradient Magnitudes Epoch 8:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 8
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 8_table
                fields: []
      Gradient Magnitudes Epoch 9:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Parameter
            value: Gradient Magnitude
          stringSettings:
            title: Gradient Magnitudes of Model Parameters - Epoch 9
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Gradient Magnitudes Epoch 9_table
                fields: []
      conf_mat:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: Confusion Matrix Test Set
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
