wandb_version: 1

dataset:
  desc: null
  value: cifar10
architecture:
  desc: null
  value: CNN_GAP
initial_lr:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 10
batch size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702650343.386548
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
